name: Test

on:
  push:
    branches: [ "release-build" ]

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  release-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build
      run: cargo build --release
    - name: upload-binary
      run: |
        zip -r gen.macos.zip target/release/gen
        gh release upload nightly gen.macos.zip --clobber

  release-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build
      run: cargo build --release
    - name: upload-binary
      run: |
        zip -r gen.ubuntu.zip target/release/gen
        gh release upload nightly gen.ubuntu.zip --clobber
