name: Test

on:
  push:
    branches: [ "release-build" ]

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  release-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: stable-x86_64-apple-darwin
    - name: Build
      run: |
        cargo build --release --target x86_64-apple-darwin
        cargo build --release
    - name: upload-binary
      run: |
        zip -j -r gen.macos-arm64.zip target/release/gen
        zip -j -r gen.macos-x86.zip target/x86_64-apple-darwin/gen
        gh release upload nightly gen.macos-arm64.zip --clobber
        gh release upload nightly gen.macos-x86.zip --clobber

  release-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build
      run: |
        cargo build --release
    - name: upload-binary
      run: |
        zip -j -r gen.ubuntu.zip target/release/gen
        gh release upload nightly gen.ubuntu.zip --clobber
